version: "3.9"

services:
  app:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./app:/app
    command: python app.py

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
